#!/bin/bash

npm run build:js

# Check if there are changes in the "dist" directory
if git diff --quiet --exit-code -- "dist/"; then
  echo "No changes in 'dist/' directory. Skipping commit."
else
  # Add changes to the staging area
  git add "dist/"

  # Commit the changes
  echo "Build committed successfully."
fi

exit $?
